add new script

diff --git a/_script b/_script
--- a/_script
+++ b/_script
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-set -euo pipefail
+#set -euo pipefail
 
 # Global variables
 _DOCKER_RESULT_FILE=$(mktemp)
@@ -9,6 +9,7 @@ _DOCKER_IMAGE=""
 _DOCKER_BUILD_ARGS=""
 _TF_ARGS=""
 _TF_PATH=""
+_TF_VAR_PATH=""
 _TF_DEFAULT_AGENT_ROLE_NAME="${_TF_DEFAULT_AGENT_ROLE_NAME:-}"
 AWS_REGION="${AWS_REGION:-ap-southeast-1}"
 ECR_REGISTRY_ID="${ECR_REGISTRY_ID:-}"
@@ -226,6 +227,36 @@ terraform() {
   fi
 
   return "${exit_code}"
+}
+
+get_tfvar_path(){
+  local env="${1}"
+
+  if [[ -z "${env}" ]]; then
+    die "Environment must be specified for get_tfvar_path"
+  fi
+
+  local tfvar_file
+  if [[ -z "${_TF_VAR_PATH}" ]]; then
+    tfvar_file="./var-${env}.tfvars"
+  else
+    tfvar_file="./${_TF_VAR_PATH}/var-${env}.tfvars"
+  fi
+
+  if [[ ! -f "${tfvar_file}" ]]; then
+    die "tfvars file not found: ${tfvar_file}"
+  fi
+
+  echo "${tfvar_file}"
+}
+
+terraform_init(){
+  if is_func "_init"; then
+    log "use _init fun"
+    _init $@
+  else
+    terraform init $@
+  fi
 }
 
 # Run Gradle in Docker container
